services:
  - type: web
    name: cricarena
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn cricarena.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cricarena.settings
      - key: PYTHON_VERSION
        value: 3.10
